### ISSUE TITLE
How to use matlab to run this project?

### ISSUE THREAD

**Issue by Alberoyang** [laurafroelich/tensor_classification#25]
Hello, I am currently using tensor to do some EEG signal processing, and some of the methods in this project are very helpful to me. But I don't how to run this project by matlab. Maybe I need some help from you! Thank you very much!

**Comment by laurafroelich** [comment]
Hi,
Can you try to explain which steps you have already taken, and where the issue arises? E.g. have you tried to run the tests and simulations? You can decrease the simulated data size to speed up the simulations.

Is there any particular method you are interested in trying out first?

**Comment by Alberoyang** [comment]
Hi,
Thanks for your reply! maybe I make a big mistake, my matlab is 2017a, and I haven't install all dependencies, and I was upgrading and installing them yesterday, now it runs. Thanks for your project,  It helped me a lot. If I have any other question, could I ask you?

**Comment by laurafroelich** [comment]
Great, I'm glad to hear it worked for you.

Yes, please do, I'm glad you can use the code.
