### ISSUE TITLE
A small mistake in the file HODA.m

### ISSUE THREAD

**Issue by zthglyg** [laurafroelich/tensor_classification#30]
As can be seen in the line26 in the file HODA.m, the command [~, lowerdims, ~, Us] = parse_varargin(sizeX, nmodes, [], varargin{1}, [], 'orth'); will return a mistake when someone call the function HODA without the varargin to specify the low dimensions. Maybe it can be changed as a switch command like this 
if (isempty(varargin))
    [~, lowerdims, ~, Us] = parse_varargin(sizeX, nmodes, [], varargin, ...
        [], 'orth');
else
    [~, lowerdims, ~, Us] = parse_varargin(sizeX, nmodes, [], varargin{1}, ...
        [], 'orth');
end

**Comment by laurafroelich** [comment]
Hi,
Thanks for the comment. Please feel free to make a pull request for faster merging of the change.
